import Link from "next/link";
import Image from "next/image";
import spatial from "@/generated/proposal-spatial.json";
import { ProposalMap } from "./proposal-map";
import { ProposalSceneVisual } from "./proposal-visual";
import { OBLIGATIONS_URL, OWED_TREES, PlantingObligations, SPOTS_IN_DRIVEWAYS, STREET_SPOTS } from "./planting-obligations";
import { stabala } from "@/lib/gup-grad/planovi-na-snazi";

const recreation = spatial.recreation;
const road = spatial.road_candidate;
const number = (value: number, digits = 0) => value.toLocaleString("hr-HR", { maximumFractionDigits: digits });
const linkStyle = "fokus inline-flex min-h-11 items-center rounded font-semibold text-maslina underline underline-offset-4 hover:text-maslina-tamna";
type TreeCandidate = { candidate_id: string; coordinates: number[]; screen_result: string; chainage_m?: number; side?: string; nearest_utility: { label: string; network_status: string }; nearest_utility_distance_m: number; planting_parcel_ids: string[] };

export function ProposalVisual({ src, alt, caption, width = 1536, height = 1024, priority = false }: { src: string; alt: string; caption: string; width?: number; height?: number; priority?: boolean }) {
  return <figure><Image src={src} alt={alt} width={width} height={height} preload={priority} sizes="(max-width: 1024px) 100vw, 992px" className="h-auto w-full rounded-xl" /><figcaption className="mt-3 max-w-3xl text-sm leading-6 text-kamen-tekst">{caption}</figcaption></figure>;
}

export function Facts({ items }: { items: [string, string][] }) {
  return <dl className="grid grid-cols-3 gap-3 border-y border-kamen-rub py-6 sm:gap-8">{items.map(([value, label]) => <div key={label}><dt className="text-sm leading-5 text-kamen-tekst">{label}</dt><dd className="mt-2 text-xl font-bold tracking-tight tabular-nums sm:text-3xl">{value}</dd></div>)}</dl>;
}

function Invitation() {
  return <section className="flex flex-wrap items-center justify-between gap-6 border-t border-kamen-rub pt-8"><div><h2 className="text-2xl font-bold tracking-tight">Što biste vi dodali?</h2><p className="mt-2 max-w-xl leading-7 text-kamen-tekst">Ovo je prijedlog za razgovor sa susjedima. Podijelite što vam je važno prije razrade projekta.</p></div><Link href="/prijavi" className="fokus inline-flex min-h-12 items-center rounded-full bg-maslina px-6 py-3 font-semibold text-white hover:bg-maslina-tamna">Dodaj svoj prijedlog</Link></section>;
}

function TreePositions({ trees }: { trees: TreeCandidate[] }) {
  return <details className="mt-5 rounded-xl border border-kamen-rub bg-white p-5">
    <summary className="fokus cursor-pointer font-semibold">Položaji {trees.length} stabala i najbliže instalacije</summary>
    <div className="mt-4 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Prijedlog položaja stabala, čestice, koordinate i udaljenosti do instalacija</caption><thead><tr className="border-b border-kamen-rub"><th className="py-3 pr-4">Stablo / čestica</th><th className="pr-4">Koordinate (širina, dužina)</th><th className="pr-4">Najbliža instalacija</th><th className="pr-4">Udaljenost</th><th>Uvjet</th></tr></thead><tbody>{trees.map((tree) => <tr key={tree.candidate_id} className="border-b border-kamen-tlo last:border-0"><th className="py-3 pr-4">{tree.candidate_id}<span className="mt-1 block whitespace-nowrap font-normal">k.č. {tree.planting_parcel_ids.map((id) => id.split(":")[1]).join(", ")}</span>{tree.chainage_m != null && <span className="mt-1 block whitespace-nowrap font-normal">{number(tree.chainage_m)} m · {tree.side === "left" ? "lijevo" : "desno"}</span>}</th><td className="whitespace-nowrap pr-4 font-mono text-xs">{tree.coordinates[1].toFixed(6)}, {tree.coordinates[0].toFixed(6)}</td><td className="pr-4">{tree.nearest_utility.label}<span className="mt-1 block text-kamen-drugi">{tree.nearest_utility.network_status === "dpu-plan" ? "DPU" : "Gradska evidencija"}</span></td><td className="whitespace-nowrap pr-4">{number(tree.nearest_utility_distance_m, 1)} m</td><td>{tree.screen_result === "conflict" ? "Prilagodba zbog instalacija" : "Terenska provjera"}</td></tr>)}</tbody></table></div>
  </details>;
}


function ImplementationDetails({ sidewalks = false }: { sidewalks?: boolean }) {
  const data = sidewalks ? road : recreation;
  const trees = sidewalks ? road.screening.candidates : recreation.planting_screen.candidates;
  return <details id="provedba" className="group border-y border-kamen-rub py-1">
    <summary className="fokus cursor-pointer py-6 text-lg font-bold">Detalji provedbe i izvori <span className="ml-2 text-sm font-normal text-kamen-tekst">Čestice, instalacije, mjere i otvorena pitanja</span></summary>
    <div className="space-y-7 pb-8 text-kamen-tekst">
      <section><h3 className="font-bold text-kamen-tinta">Čestice i obuhvat</h3>
        {sidewalks ? <><p className="mt-2 leading-7">Svi krugovi sadnje polumjera 1 m nalaze se unutar cestovne čestice 419/9, k.o. Split. Ona pokriva oko {number(road.cadastre.covered_length_m)} m odabrane ceste. Sljedećih {number(road.cadastre.unconfirmed_length_m, 1)} m prolazi česticom 297/2 bez potvrđenog cestovnog statusa; za posljednjih {number(road.cadastre.missing_cadastre_length_m, 1)} m nedostaje katastarska geometrija. Na tim dijelovima stabla nisu predložena.</p><p className="mt-2 leading-7">Radna dopuna nogostupa širine do 1,8 m ograničena je na cestovnu česticu i ne prekriva evidentirane nogostupe. Duljine praznina mjerene su duž osi, zasebno za svaku stranu; raskrižja i izostanak zapisa treba provjeriti na terenu.</p></> : <><p className="mt-2 leading-7">Zona R2, oznaka 1.15 iz nacrta GUP-a 2024., ima približno {number(recreation.area_m2)} m² i rub duljine {number(recreation.perimeter_m, 1)} m. Zahvaća dijelove čestica 419/1 i 419/9, k.o. Split. Cijela čestica 419/1 ima oko {number(recreation.parcel_419_1_area_m2)} m²; ona nije isto što i obuhvat prijedloga.</p><p className="mt-2 leading-7">Cageball zauzima radnu plohu 22 × 9 m na srednjoj terasi, teretana 8 × 6 m na gornjoj, a dječja igra približno 637 m² niže terase. Parkiranje je pomaknuto zapadno od donje terase: povezani zahvat izvan R2 na dijelovima čestica 419/1 i 419/9. Tri mjesta, manevar i pristup treba potvrditi prometnim projektom. To su površine za prostornu provjeru, a ne potvrđene izvedbene dimenzije. Prethodne plohe 28 × 12 m i 10 × 12 m povučene su od vidljivih postojećih zelenih pojaseva. Dimenzije i zaštitu korijena treba potvrditi snimkom. Prenamjenu parkiranja, pristup i uvjete na cestovnoj čestici treba usuglasiti s Gradom.</p><p className="mt-2 leading-7">DGU-ov model terena, mreža približno 3 m, pokazuje oko 46 m na donjoj terasi, 47–48 m na srednjoj, 48–49 m prema gornjem dijelu parka i 50–52 m uz južnu cestu. Ne određuje točnu visinu zida. U 3D modelu prikazane su radne ravnine oko 46,5 m za dječju igru, 48 m za cageball i 48,8 m za teretanu. Gornja ravnina pretpostavlja najmanje 0,8 m razlike prema srednjoj, prema korisnikovim fotografijama; to nisu izmjerene projektne kote. Zid je približno modeliran iz visina s obje strane označenog ruba. Potrebna je geodetska snimka kota, zida i prijelaza između terasa; pristupačan ulaz i veze među sadržajima moraju se zasebno projektirati.</p></>}
      </section>
      {!sidewalks && <section><h3 className="font-bold text-kamen-tinta">Zašto padel zasad nije uključen</h3><p className="mt-2 leading-7">Padel traži unutarnji teren 20 × 10 m, uz ogradu i pristup. U radnom obuhvatu srednje terase provjerene su obje orijentacije usporedne s postojećim igralištem, uz veći cageball i dodatni metar oko plohe. Nije pronađen raspored koji stane. To ne zamjenjuje geodetsku snimku i projektantsku provjeru drugih mogućnosti.</p><a href={recreation.program.padel.source} className={linkStyle}>FIP · dimenzije padel terena</a></section>}
      <section><h3 className="font-bold text-kamen-tinta">Sadnja i instalacije</h3><p className="mt-2 leading-7">Provjera uključuje dostupne gradske vodove i pouzdano izdvojene trase iz DPU-a. {sidewalks ? "Razmak od 3 m radni je kriterij, a ne propisani zaštitni pojas." : "Za nove platane rezervirane su otvorene sadne plohe polumjera 2 m; radni probir od osi voda iznosi 5 m. Taj krug nije dovoljan prikaz ukupnog prostora korijena. Potrebno je projektirati povezano tlo, odvodnju, zaštitu zidova i instalacija."} Sadni krugovi ne ulaze u evidentirane nogostupe, radne dopune ni prometne plohe DPU-a na razini terena. Provjerene su i postojeće zgrade.{!sidewalks && <> U R2 je predložena prenamjena bočne ceste: njezin dosadašnji kolnik zamjenjuje se stazom i zelenilom, uz očuvanje potrebnog pristupa zgradama i službama. Nova sadnja ne ulazi u sportske plohe, stazu ni ucrtane postojeće zelene pojaseve; dječje sprave treba rasporediti oko stabala.</>}</p>
      {sidewalks && <><p className="mt-2 leading-7">Od {road.screening.candidates.length} položaja, {road.screening.suggested} prolaze početni odmak od vodova, a {road.screening.conflict} ovise o zaštiti ili izmještanju instalacije. {SPOTS_IN_DRIVEWAYS.length > 0 && `Mjesta ${SPOTS_IN_DRIVEWAYS.join(" i ")} su u kolnim ulazima hale Dračevac 7A i otpadaju.`} Dio sadnih površina ima vrlo malen rubni razmak unutar čestice: precizna snimka može smanjiti broj izvedivih mjesta.</p><p className="mt-2 leading-7">Gušći raspored traži položaje svakih 10 m, uz najmanje 8 m između novih stabala. Sadni krug polumjera 1 m prikazuje samo otvoreno tlo, ne ukupni prostor za korijen. Za veće krošnje potrebno je povezano tlo ispod zelenih traka i propusnih površina, bez sužavanja nogostupa. Krošnje promjera 6, 8 i 10 m radni su scenariji razvoja prema odmaku od zgrada i raspoloživoj širini. Veće platane razmatraju se na prostranijim mjestima; konačan izbor vrste ovisi o tlu i instalacijama.</p><h3 className="mt-5 font-bold text-kamen-tinta">Postojeća sadnja i 3D podloga</h3><p className="mt-2 leading-7">Na DGU ortofotu približno je označeno pet skupina postojeće sadnje i pet prilaza. Nova sadna mjesta izmiču tim zonama. Red maslina uz česticu 291 predlažemo zamijeniti visokim stablima (vidi „Tko sadi”). To nije potpun inventar debala, korijena ili pristupa: prije radova potrebna je terenska snimka.</p><p className="mt-2 leading-7">3D prikaz i karta koriste iste položaje. Teren prati DGU model reljefa, mreže približno 3 m, bez povećavanja visina. Okolne zgrade i postojeća stabla prikazani su na ortofotu; njihove visine nisu modelirane. Izvorna fotografija već sadrži sjene. Detaljnija AI podloga približno je poravnata prema zajedničkim orijentirima; ne određuje položaje, katastar ili postojeće stanje. Izvorni ortofoto ostaje dostupan u odabiru podloge. Promjena smjera sunca pokazuje samo shematske sjene nove sadnje, bez datuma, godišnjeg doba ili izračuna postotka hlada.</p></>}
      {!sidewalks && <><h3 className="mt-5 font-bold text-kamen-tinta">Postojeća stabla određuju raspored</h3><p className="mt-2 leading-7">Lokalni gradski sloj nema zapisa unutar ovog parka. Prema ortofotu i fotografijama približno su označene tri skupine: stablo uz kućicu na sjevernom rubu, sadnja između parkiranja i igrališta te zeleni otoci uz zapadni prilaz i vježbalište. To nije popis ni točna snimka debala. Vidljiva stabla zadržavaju se, a vrsta, stanje, položaj i zona zaštite korijena trebaju terensku provjeru.</p><p className="mt-2 leading-7">Predložena su {recreation.shade.new_trees} nova mjesta za platane; {recreation.shade.conditional_trees} traži usklađivanje s vodovima prema radnom probiru. I preostalo mjesto zahtijeva provjeru tla i stvarnih instalacija. Prikazana krošnja promjera 10 m ilustrira budući razvoj, a ne neposredan hlad nakon sadnje ili najveću veličinu vrste. Nije riječ o simulaciji sjene po satima.</p><a href={recreation.shade.species_source} className={linkStyle}>RHS · razvoj i potrebe platane</a></>}
      <p className="mt-2 leading-7">Evidencija stabala nije potpuna. Postojeća stabla treba snimiti i sačuvati gdje je moguće. {sidewalks ? "3D plan je idejni prikaz temeljen na istim podacima kao karta; za izvedbu su potrebni projekt i terenska snimka." : "3D plan koristi položaje s karte; raspored sprava, ravnine terasa i zid idejni su prikaz. Izvedbu treba razraditi projektom i terenskom snimkom."}</p><TreePositions trees={trees} /></section>
      {sidewalks && <section><h3 className="font-bold text-kamen-tinta">Evidentirani nogostupi</h3><div className="mt-3 overflow-x-auto"><table className="w-full text-left text-sm"><caption className="sr-only">Dijelovi postojećih nogostupa od zapada prema istoku</caption><thead><tr className="border-b border-kamen-rub"><th className="py-3">Strana</th><th>Duljina</th><th>Širina</th></tr></thead><tbody>{road.sidewalks.records.map((r,i) => <tr key={i} className="border-b border-kamen-tlo"><td className="py-3">{r.side === "left" ? "Lijeva" : "Desna"}</td><td>{number(r.length_m, 1)} m</td><td>{number(r.width_m, 1)} m</td></tr>)}</tbody></table></div></section>}
      <section><h3 className="font-bold text-kamen-tinta">DPU radne zone Dračevac</h3><p className="mt-2 leading-7">{sidewalks ? `DPU obuhvaća oko ${number(road.dpu.target_covered_length_m, 1)} m zapadnog kraja odabrane ceste.` : "R2 leži izvan granice DPU-a, uz njegov istočni rub. Izvorni prometni list prikazuje i spojeve nogostupa preko te granice."} Na karti su dostupni izvorni nogostupi i kolnici, odvojeni po razinama, te trase vode, odvodnje, struje, telekoma i plina. Planski prikaz ne potvrđuje izvedeno stanje.</p></section>
      <section><h3 className="font-bold text-kamen-tinta">Izvori i podaci</h3><p className="mt-2 leading-7">GIS Grada Splita: katastar, ceste, nogostupi, oprema i instalacije. DGU: DOF 2023. i digitalni model reljefa, Otvorena dozvola. {spatial.method}</p><div className="mt-3 flex flex-wrap gap-x-6 gap-y-1"><a className={linkStyle} href={recreation.source_pdf}>Nacrt GUP-a 2024.</a><a className={linkStyle} href="https://split.hr/DesktopModules/Bring2mind/DMX/API/Entries/Download?Command=Core_Download&EntryId=14243&PortalId=0&language=hr-HR">DPU · prometni list</a><a className={linkStyle} href={`/geo/prijedlozi/${sidewalks ? "nogostupi" : "rekreacija"}.geojson`}>Preuzmi podatke prijedloga</a><Link className={linkStyle} href={`/karta?pogled=katastar&podloga=dof&sloj=katastar&sloj=nogostupi&c=${(data.bounds[1]+data.bounds[3])/2},${(data.bounds[0]+data.bounds[2])/2}&z=18`}>Otvori izvornu kartu</Link></div></section>
    </div>
  </details>;
}

export function RecreationProposal() {
  return <div className="space-y-10 sm:space-y-14">
    <ProposalSceneVisual key="rekreacija" kind="rekreacija" />
    <Facts items={[[`≈ ${number(recreation.area_m2)} m²`, "Rekreativna zona"], [`${recreation.shade.new_trees} platane`, "Nova mjesta za velike krošnje"], ["3 terase", "Igra · sport · vježbanje"]]} />
    <section className="grid gap-6 sm:grid-cols-[1fr_1.25fr]"><h2 className="max-w-sm text-3xl font-bold leading-tight tracking-tight">Djeci cijela terasa.<br />Sportu više mjesta.</h2><div className="space-y-4 text-lg leading-8 text-kamen-tekst"><p>Najnižu terasu u cijelosti prepustiti dječjoj igri. Srednju iskoristiti za veći cageball teren, a na gornjoj urediti teretanu na otvorenom.</p><p>Bočnu cestu uz zapadnu zgradu pretvoriti u šetnicu sa stablima, grmljem i klupama. Tri parkirna mjesta premjestiti zapadno od donje terase, uz njezin sjeverni pristup.</p></div></section>
    <section className="grid gap-8 sm:grid-cols-2"><div><h2 className="text-xl font-bold">Igra za različite uzraste</h2><p className="mt-3 leading-7 text-kamen-tekst">Na donjoj terasi ima mjesta za penjanje, ljuljanje, igru najmlađih i predah roditelja. Cageball dobiva veći, mrežom ograđen teren. Padel zasad nije uključen: radni raspored ne ostavlja dovoljno prostora uz veći teren i prolaze.</p></div><div><h2 className="text-xl font-bold">Zelena veza između razina</h2><p className="mt-3 leading-7 text-kamen-tekst">Pješačka staza vodi uz terase, kroz hlad i mjesta za sjedenje. Park prati postojeće visine; južna cesta ostaje iznad njega, iza potpornog zida. Pristupačne veze i nužan pristup susjednim zgradama dio su daljnje razrade.</p></div></section>
    <section className="grid gap-6 sm:grid-cols-[1fr_1.25fr]"><h2 className="max-w-sm text-3xl font-bold leading-tight tracking-tight">Više hlada.<br />Čuvamo ono što raste.</h2><div className="space-y-4 text-lg leading-8 text-kamen-tekst"><p>Postojeći drvored, stablo uz kućicu i zelene otoke uklapamo u uređenje. Igralište i teretana povučeni su od vidljive sadnje. Raspored sadržaja prati postojeću sadnju.</p><p>Četiri nova mjesta za platane s velikim krošnjama nadopunjuju hlad nad dječjom igrom, klupama i šetnicom. Oko njih ostaju otvorene sadne površine, a sprave i sjedenje raspoređuju se prema stablima.</p><p className="text-base leading-7">Veći hlad dolazi s razvojem krošnji. Nova sadnja ovisi o prostoru za korijen i rješavanju instalacija; 3D prikaz pokazuje mogući budući izgled.</p></div></section>
    <section id="prijedlog"><h2 className="text-2xl font-bold tracking-tight">Razgledajte raspored</h2><p className="mb-5 mt-2 max-w-2xl leading-7 text-kamen-tekst">Dodirnite sadržaj na karti. Prikazani su sadržaji po terasama, šetnica i premješteno parkiranje. Tamnozeleni pojasevi označavaju postojeću sadnju koju čuvamo, a prozirni krugovi moguću buduću veličinu novih krošnji. Crvene sadne točke traže usklađivanje s instalacijama.</p><ProposalMap url="/geo/prijedlozi/rekreacija.geojson" label="Dječje igralište dolje, cageball u sredini, teretana gore, zapadna šetnica i parkiranje" /></section>
    <details className="border-t border-kamen-rub pt-5"><summary className="fokus cursor-pointer py-2 font-semibold">Kako prostor izgleda danas</summary><div className="mt-5 grid gap-6 sm:grid-cols-2"><ProposalVisual src="/prijedlozi/rekreacija-ortofoto.jpg" width={1200} height={1020} alt="Postojeće igralište i parkiralište na ortofotu" caption="Postojeće stanje · DOF 2023., DGU, Otvorena dozvola." /><ProposalVisual src="/prijedlozi/rekreacija-gup.png" width={650} height={550} alt="Zona R2 u nacrtu GUP-a 2024." caption="Izvorni nacrt GUP-a 2024. · zona R2, izmjena 1.15." /></div></details>
    <ImplementationDetails />
    <Invitation />
  </div>;
}

export function SidewalkProposal() {
  const spots = STREET_SPOTS;
  return <div className="space-y-12 sm:space-y-16">
    <section className="space-y-8">
      <div className="max-w-3xl space-y-4 text-lg leading-8 text-kamen-tekst">
        <p>Cesta Dračevac kroz poslovnu zonu duga je {number(road.length_m)} metara i nema drvoreda. Predlažemo ga uz nogostup, na {spots} mjesta unutar cestovne čestice.</p>
        <p>Nije sve na Gradu. Susjedne građevine po planu ili dozvoli duguju {stabala(OWED_TREES)} na vlastitim česticama, a nijedno nije posađeno kako se traži. Gdje stanu uz ulicu, ta stabla hlade i nogostup, a ponegdje zamjenjuju mjesta na nogostupu koja su preblizu podzemnim vodovima.</p>
      </div>
      <Facts items={[[`${number(road.length_m)} m`, "ulice bez drvoreda"], [String(spots), "mjesta uz nogostup"], [String(OWED_TREES), "stabala duguju susjedi"]]} />
    </section>
    <section id="prijedlog" className="scroll-mt-20">
      <h2 className="text-2xl font-bold tracking-tight">Karta ulice</h2>
      <p className="mb-5 mt-2 max-w-3xl text-base leading-7 text-kamen-tekst">Zelene točke su mjesta uz nogostup, crvene su blizu podzemnih vodova. Ljubičasto su stabla koja duguju susjedne građevine. Sivo zaokružena mjesta na nogostupu otpadaju: kad susjed posadi svoje stablo ili jer su u kolnom ulazu. Dodirnite oznaku za pojedinosti.</p>
      <ProposalMap url="/geo/prijedlozi/nogostupi.geojson" extraUrls={[OBLIGATIONS_URL]} label="Karta ulice Dračevac: mjesta za stabla uz nogostup i stabla koja duguju susjedne građevine" sidewalks />
    </section>
    <PlantingObligations />
    <section className="space-y-4">
      <h2 className="text-2xl font-bold tracking-tight">Ulica s razvijenim krošnjama</h2>
      <p className="max-w-3xl text-base leading-7 text-kamen-tekst">3D prikaz pokazuje mjesta uz nogostup, s krošnjama kakve stabla dobiju s godinama. Stabla na susjednim česticama u njemu nisu.</p>
      <ProposalSceneVisual key="nogostupi" kind="nogostupi" />
    </section>
    <ImplementationDetails sidewalks />
    <Invitation />
  </div>;
}
